image:
  - Visual Studio 2015
install:
  # Grab a current link from: http://unity3d.com/get-unity/download/archive
  - curl -fsS -o UnityInstaller.exe http://netstorage.unity3d.com/unity/2860b30f0b54/Windows64EditorInstaller/UnitySetup64-5.6.1f1.exe
  # Install silently: https://docs.unity3d.com/Manual/InstallingUnity.html
  - UnityInstaller.exe /S
build_script:
  - ps: |
      &"C:/Program Files/Unity/Editor/Unity.exe" `
      -batchmode `
      -nographics `
      -silent-crashes `
      -projectpath "$pwd" `
      -buildWindows64Player "$pwd/output.exe" `
      -logFile '$pwd/unity-build-log.txt' `
      -quit
  - ps: cat '$pwd/unity-build-log.txt'
artifacts:
  - path: output.exe
    name: output
