image:
  - Visual Studio 2015
install:
  # Grab a current link from: http://unity3d.com/get-unity/download/archive
  - curl -fsS -o UnityInstaller.exe http://netstorage.unity3d.com/unity/2860b30f0b54/Windows64EditorInstaller/UnitySetup64-5.6.1f1.exe
  # Install silently: https://docs.unity3d.com/Manual/InstallingUnity.html
  - UnityInstaller.exe /S
build_script:
  # Run Unity in batch mode: https://docs.unity3d.com/Manual/CommandLineArguments.html
  # Pipe the output so that Powershell waits for the command to finish.
  - ps: |
      &"C:/Program Files/Unity/Editor/Unity.exe" `
      -batchmode `
      -nographics `
      -silent-crashes `
      -projectpath "$pwd" `
      -buildWindows64Player "$pwd/unity-build-output.exe" `
      -logFile '$pwd/unity-build-log.txt' `
      -quit `
      | Out-Default
  # Print the Unity log to the console.
  - ps: cat '$pwd/unity-build-log.txt'
artifacts:
  - path: unity-build-output.exe
    name: output
  - path: unity-build-log.txt
    name: log
