version: 2.1
jobs:
  build:
    docker:
      - image: gableroux/unity3d:2019.3.0f6-windows
      # https://gitlab.com/gableroux/unity3d
    steps:
      - run:
          name: Install Unity License
          command: |
            mkdir -p ~/.cache/unity3d
            mkdir -p ~/.local/share/unity3d/Unity/
            echo $UNITY_2019_3_LICENSE_BASE64 | base64 --decode > ~/.local/share/unity3d/Unity/Unity_lic.ulf
          # License process is described well here: https://gitlab.com/gableroux/unity3d-gitlab-ci-example#how-to-activate
          # The easiest way to inject the license file into our builds is with an environment variable. However,
          # line breaks are lost if we just copy-paste the text. Instead, we base64-encode the license content and then
          # decode it when we write the variable into a license file.
      - run:
          name: Run Unity
          command: |
            /opt/Unity/Editor/Unity \
            -quit \
            -batchmode \
            -nographics \
            -logFile /dev/stdout \
            -executeMethod Mapzen.Unity.Editor.Project.ExportPackage
      - store_artifacts:
          name: Store Unity package output
          path: tangram-unity.unitypackage
          destination: Package
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
